### ISSUE TITLE
multibar.create will return undefined in github actions (noTTY env)

### ISSUE THREAD

**Issue by bluelovers** [npkgz/cli-progress#117]
```ts
const bar: SingleBar = multibar.create(200, 0);
```

**Comment by AndiDittrich** [comment]
any more details ? could you provide a full "minimal" example howto reproduce the issue including the github actions yaml ?

**Comment by bluelovers** [comment]
https://github.com/bluelovers/idea-l10n-zht/runs/4795261036?check_suite_focus=true

https://github.com/bluelovers/idea-l10n-zht/commit/5171be6df620c100e82b9596641789647a41ad29

**Comment by AndiDittrich** [comment]
i would assume that you've forgot to set the `noTTYOutput` flag and github actions doesn't emulate a tty environment - https://github.com/npkgz/cli-progress#options-1

in this case the issue is caused by [this line](https://github.com/npkgz/cli-progress/blob/master/lib/multi-bar.js#L35)

atm i'm not sure about howto "solve" this issues for future release

**Comment by bluelovers** [comment]
return dummy fake api object

**Comment by AndiDittrich** [comment]
such kind of workaround may introduce recursions in the future - some kind of refactoring is required
